import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "@/contexts/auth.context";
import { ResumeProvider } from "@/contexts/resume.context";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${poppins.className}`}  suppressHydrationWarning>
        <main>
          <Provider>
            <ResumeProvider>
              {children}
              <Toaster richColors position="top-right" />
            </ResumeProvider>
          </Provider>
        </main>
      </body>
    </html>
  );
}
